### ISSUE TITLE
Conflicts with the ValvePython/steam package

### ISSUE THREAD

**Issue by Laeborg** [deivit24/python-steam-api#11]
Namespace seems to conflict with the ValvePython/steam package.

Is it possible to change dir name to steam-web-api or something similar instead?

**Comment by deivit24** [comment]
Hey sorry for just getting back to you on this. Been busy with work! Just so I understand this correctly, there is a ValvePython package and you are trying to import something that has the same steam directory name and it conflicts with our steam directory?

**Comment by Laeborg** [comment]
Exactly!
ValvePython/steam is widely used, so I think the correct solution would be to change the dir name for this package.

**Comment by deivit24** [comment]
Is there a way for the time being to alias for now? Or does it still have a conflict? Can I see an error message?

I want to see If I can replicate the issue

**Comment by mscheltienne** [comment]
@deivit24 Both your package and https://github.com/ValvePython/steam are called `steam`, thus `import steam` yields a conflict if both packages are installed in the same environment.
I agree with @Laeborg that your package being less used, it would be nice if you could rename it.

**Comment by deivit24** [comment]
@mscheltienne Sounds good. sorry for just getting back, since I got no reply last time, I thought it was not an issue. Will work on this over the weekend. Goal to have a release with this change
