### ISSUE TITLE
How to use the filters in get_app_details

### ISSUE THREAD

**Issue by zheage** [deivit24/python-steam-api#12]
I'm having trouble when trying to use the function `get_app_details `to search for specific informations of games. 

The code is:

`game_id = 1048250

user = steam.apps.get_app_details(game_id, country = "BR", filters = "name,platforms,price_overview")`

the response:

`{'1048250': {'success': True,
  'data': {'platforms': {'windows': True, 'mac': False, 'linux': False}}}}`

I tryed to pass a list as input of filters parameter and isn't work too. Can someone help me?

![image](https://github.com/deivit24/python-steam-api/assets/64561071/63613a6a-1c90-4d3c-99a1-75f5245a5b50)

**Comment by UnreleasedDev** [comment]
filters only accepts `str` or `None` convert list to `str` before passing 

something like this should work

```
filters_list = ["name", "platforms", "price_overview"]
filters_str = ','.join(filters_list)
game_id = 1048250
user = steam.apps.get_app_details(game_id, country="BR", filters=filters_str)
print(user)
```
