### ISSUE TITLE
Incorrect encoding

### ISSUE THREAD

**Issue by TiroMaks** [deivit24/python-steam-api#33]
When you change the country in the search query, the response does not come in UTF-8 encoding

With this error (see screenshot) I came across it when the Cyrillic alphabet appeared in the response
![Example](https://github.com/deivit24/python-steam-api/assets/118979429/dd520e55-adfb-4ec0-a404-ce80f0120617)

**Comment by TiroMaks** [comment]
The same error occurs when receiving information about the game
`steam.apps.get_app_details(292030)`

![Example](https://github.com/deivit24/python-steam-api/assets/118979429/82d1892b-3ca4-428b-ac44-04c7c708a542)

**Comment by deivit24** [comment]
@TiroMaks Hey. I was able to replicate and fix the first issue in the search query. I am actually web scraping for that function. 

However, I am not able to replicate it on the get_app_details. I tried and I am getting the correct encoding. Is there anyway you can provide more details so I can try to replicate it?
![Screenshot 2024-05-26 at 8 54 41 PM](https://github.com/deivit24/python-steam-api/assets/35977452/51df9ef6-ea74-46f3-9675-968a19d7cc95)

**Comment by deivit24** [comment]
@TiroMaks Maybe the browser you are using is doing this?

**Comment by deivit24** [comment]
Going to close this issue. I could not replicate the issue with get_app_details but was able to fix the issue with the search. 

If the get_app_details issue continues, can you please open up another issue and provide a little for details on how to replicate it
