### ISSUE TITLE
Response in the request language in `get_app_details`

### ISSUE THREAD

**Issue by TiroMaks** [deivit24/python-steam-api#39]
When requesting `get_app_details` with the country selection parameter, a response was received in the language of the selected country (description, name...).

Or is it impossible, since Steam does not store such data?

**Comment by deivit24** [comment]
Hey sorry for the late response. Been busy with work and going to make more of an effort to answer. It looks like they do not have that data from what I can tell. I think it might js on the browser that might update the language. Not sure
