### ISSUE TITLE
steam.apps.get_app_details() returns string instead of dict

### ISSUE THREAD

**Issue by Aliefe02** [deivit24/python-steam-api#5]
steam.apps.get_app_details() function was supposed to return a dict value but it returns a string. Format of the string is for dict (for example there are "{ }" and "path: ") however there are some problems. True and False values are written as true and false. No capital T and F. I think this causes function to return values as string instead of dict. when i copy the returned value and correct true and false values to True and False and give this data to a variable python recognizes it as a dictionary. Pls fix this issue i really need this API (It's great btw)

**Comment by PsiPi-Codes** [comment]
So I believe this issue occurs because of the way it obtains the information. Python Steam API obtains the app details using json.request(), it then processes this information using json.load(). However json doesn't use True or False for boolean values, it uses true or false (no capitalization), that may be what is causing the error. I'll reply to this when I figure out a fix to this if you would like that.

**Comment by PsiPi-Codes** [comment]
Hello.

So I found the problem, the get_app_details() method returns json.dumps(json_loaded_response). The Issue isn't the way json and python write boolean values, it is this return function. json.dumps() returns a string, so even though it originally is a dictionary, it returns a string version of that dictionary. Removing json.dumps() from the return for the method fixes the issue.
![image](https://github.com/deivit24/python-steam-api/assets/140664373/a343cb4e-3a87-4498-b84d-2e1432545050)
This is the method
![image](https://github.com/deivit24/python-steam-api/assets/140664373/6e258c6e-3079-48b2-8208-35dae59afb21)
Remove json.dumps() and leave json_loaded_response, like this:
![image](https://github.com/deivit24/python-steam-api/assets/140664373/08cc2836-7719-46b6-919f-624a5223c541)
Then save the file, it should return a dictionary now. 

If you have trouble finding the method, please feel free to contact me, but that solved it for me ^^

**Comment by Aliefe02** [comment]
Thanks a lot

**Comment by deivit24** [comment]
Thank you! If you want to create a PR and push, you can! Don't mind if people want to contribute. If not no worries! I will do it when I get home and update the package

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PsiPi-Codes** [comment]
I'm rather new to github (just made my account right now to resolve this issue) so I'll _try_ to do the pull request, however if I can't finish it by today then that would be great, thank you for providing me and everyone else with this API, it has helped a lot with my own project.

**Comment by deivit24** [comment]
No worries! Thanks that means alot!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PsiPi-Codes** [comment]
I believe I have sent the pull request, please tell me if it worked (this is my first time).

**Comment by deivit24** [comment]
Will let you know when I get home (tomorrow)!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PsiPi-Codes** [comment]
Got it! Thank you.
